### ISSUE TITLE
group template add

### ISSUE THREAD

**Issue by obfuscaten** [RediCloud/cloud-v1#115]
### Console Error

```
Put the paste.gg link or text here.
```

/

### Bug Description

Wenn ich zu einer Gruppe ein Template hinzufügen möchte, funktioniert es nicht, da das Template nicht existieren würde, obwohl es existiert.
![Termius_sle4ihbghm](https://user-images.githubusercontent.com/100081670/183974662-78abd3e5-258b-45ff-97c5-c9c6b0361eb7.png)

### Steps to Reproduce

1. template list
2. group template add Proxy Proxy

### Expected Behavior

Das Template wird zur Gruppe hinzugefügt.

### Software/Hardware

Ubuntu 20.04
Java 16

### Cloud-Version

Version: 1.5.1-RELEASE | Git: 6740dcfc

**Comment by paulkczw** [comment]
![image](https://user-images.githubusercontent.com/44299323/184016556-0e9de556-f870-4b17-88c4-67f676b41102.png)
Maybe try latest 1.6-SNAPSHOT

**Comment by paulkczw** [comment]
confirmed

**Comment by paulkczw** [comment]
fix: #122
