### ISSUE TITLE
Group Version ändern können

### ISSUE THREAD

**Issue by abgxhoben** [RediCloud/cloud-v1#126]
### Problem Description

Ich möchte die Version von ein bestehenden Gruppe ändern

### Solution Description

Group Version CMD

**Comment by paulkczw** [comment]
group edit <yourgroup> service_version <yourversion> ??

**Comment by abgxhoben** [comment]
Geht das ?

**Comment by paulkczw** [comment]
klar xd

**Comment by abgxhoben** [comment]
oh wo kann ich die ganzen Befehle sehen eyyy ;C
