### ISSUE TITLE
MAX_PLAYERS Variable nicht gefunden

### ISSUE THREAD

**Issue by obfuscaten** [RediCloud/cloud-v1#132]
### Console Error

```
Put the paste.gg link or text here.
```
![Termius_VsgEYAyy7q](https://user-images.githubusercontent.com/100081670/185661008-c8c286d0-ba5f-4d5d-b63f-30c48942b0eb.png)

### Bug Description

Er findet MAX_PLAYERS bei dem group edit Befehl nicht.

### Steps to Reproduce

1. group edit Proxy MAX_PLAYERS 120

### Expected Behavior

Die Maximale Spieleranzahl sollte sich zu **120** verändern.

### Software/Hardware

Java 16
Ubuntu 20.04 

### Cloud-Version

Version: 1.6.7-RELEASE | Git: 6114b6ce

**Comment by paulkczw** [comment]
Use the cloud or bukkit/bungee api to set max players
