### ISSUE TITLE
Error in service factory thread

### ISSUE THREAD

**Issue by obfuscaten** [RediCloud/cloud-v1#135]
### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/9821f41c888a4101876b56b10dad67f3

### Bug Description

Wenn die Cloud startet, wird der Fehler "Error in service factory thread" gespammt.

### Steps to Reproduce

1. Cloud System gestartet

### Expected Behavior

Die Cloud hätte normal gestartet

### Software/Hardware

Java 16
Ubuntu 20.04

### Cloud-Version

Version: 1.6.8-RELEASE | Git: eea0daf5

**Comment by paulkczw** [comment]
1.6.8 use a new redis structure to optimize the query connection count. Try to recreate your groups (delete and create the group's) and nodes (stop the cloud, delete node.json and the redis entry and start the cloud)
