### ISSUE TITLE
MAX_PLAYERS Property im Group Edit Befehl 

### ISSUE THREAD

**Issue by obfuscaten** [RediCloud/cloud-v1#137]
### Problem Description

Wenn man auf schnelle die Spieleranzahl einer Gruppe ändern möchte, funktioniert es nicht, da es keine andere Möglichkeit gibt diese zu ändern, außer durch die API.

### Solution Description

Man fügt im **GROUP EDIT** Befehl eine neue Property hinzu, die **MAX_PLAYERS** heißt.

**Comment by kunseru** [comment]
Finde ich eine sehr gute Idee, vor allem für Netzwerke die keine Developer haben, sondern Download Plugins.

**Comment by paulkczw** [comment]
added: [4a592ab](https://github.com/RediCloud/cloud/commit/4a592abe86663570a70b6c362f39d22b969a380f)
