### ISSUE TITLE
Dynamic Help Command

### ISSUE THREAD

**Issue by CodedInfinityFlo** [RediCloud/cloud-v1#86]
### Problem Description

Not all commands are displayed on help command

### Solution Description

Load the Content for the Help Response dynamic from the Commandmanager, because it is very useful to see all possible commands.

**Comment by paulkczw** [comment]
added: [b4c0396](https://github.com/RediCloud/cloud/commit/b4c03961183dc394672914cd9dc730e78adaddf1)
