### ISSUE TITLE
Logs dosn't work

### ISSUE THREAD

**Issue by Mischmaschine** [RediCloud/cloud-v1#88]
### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Log-Files are empty - no error

### Steps to Reproduce

-

### Expected Behavior

Logs should be filled with the messages which are also printed in the console

### Software/Hardware

-

### Cloud-Version

Git-Hash: f01a1ba1
Version: 1.3.0-SNAPSHOT

**Comment by paulkczw** [comment]
this will fix it: [67f1656](https://github.com/RediCloud/cloud/commit/67f16561e2819c8457b08502f0f90c091901d6e4)
use build for testing: http://jenkins.suqatri.net:8443/job/redi-cloud/job/dev/129/
