### ISSUE TITLE
group edit error

### ISSUE THREAD

**Issue by obfuscaten** [RediCloud/cloud-v1#92]
### Console Error

https://paste.gg/p/anonymous/d321d20f72944d009899b6ac9ab1a052

### Bug Description

Nachdem ich in der Proxy-Gruppe Wartungsarbeiten auf true & false gestellt habe.
Die Gruppe wurde bearbeitet nur kam halt nen Fehler

### Steps to Reproduce

- group edit Proxy maintenance true
- group edit Proxy maintenance false

### Expected Behavior

Es wäre kein Fehler gekommen idk

### Software/Hardware

Java Version: 16
OS: Ubuntu 20.04

### Cloud-Version

Version: 1.3.4-RELEASE | Git: 3f6f6a0c

**Comment by paulkczw** [comment]
Cannot be reproduced. I think its fixed. Try latest build
